modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
    modId = "kubejspowah"
    version = "${file.jarVersion}"
    displayName = "KubeJSPowah"
    authors = "BobVarioa"
    description = '''

    '''
[[dependencies.kubejspowah]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejspowah]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejspowah]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[2001.6.4-build.95,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejspowah]]
    modId = "powah"
    mandatory = true
    versionRange = "[5.0.4,)"
    ordering = "NONE"
    side = "BOTH"