modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
[[mods]]
    modId = "kubejspowah"
    version = "${file.jarVersion}"
    displayName = "KubeJSPowah"
    authors = "BobVarioa"
    description = '''

    '''
[[dependencies.kubejspowah]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejspowah]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejspowah]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[1902.6.1-build.234,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejspowah]]
    modId = "powah"
    mandatory = true
    versionRange = "[0.0.0,)" # this is apparently their version???
    ordering = "NONE"
    side = "BOTH"